Categories:
  - System
  - Connectivity
  - Security
License: AGPL-3.0-or-later
AuthorName: ClearSpace Contributors
AuthorEmail: etherdancer.zero553@aleeas.com
SourceCode: https://gitlab.com/example/ClearSpace
IssueTracker: https://github.com/Etherdancer/ClearSpace/issues
Donate: https://github.com/Etherdancer/ClearSpace

AutoUpdateMode: None
UpdateCheckMode: None

CurrentVersion: 0.3.2.1_alpha
CurrentVersionCode: 9

RepoType: git
Repo: https://github.com/Etherdancer/ClearSpace

Builds:
  - versionName: '0.3.2.1_alpha'
    versionCode: 9
    commit: 'v0.3.2.1_alpha'
    subdir: app
    gradle:
      - 'yes'

