package app.clearspace.network.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006C51)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF89F8D0)
val OnPrimaryContainerLight = Color(0xFF002116)
val SecondaryLight = Color(0xFF4C6359)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCEE9DB)
val OnSecondaryContainerLight = Color(0xFF092017)
val TertiaryLight = Color(0xFF3F6375)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC3E8FD)
val OnTertiaryContainerLight = Color(0xFF001F2B)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFFBFDF9)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFFBFDF9)
val OnSurfaceLight = Color(0xFF191C1B)

val PrimaryDark = Color(0xFF6CDBB5)
val OnPrimaryDark = Color(0xFF003829)
val PrimaryContainerDark = Color(0xFF00513C)
val OnPrimaryContainerDark = Color(0xFF89F8D0)
val SecondaryDark = Color(0xFFB2CCBF)
val OnSecondaryDark = Color(0xFF1E352C)
val SecondaryContainerDark = Color(0xFF354B42)
val OnSecondaryContainerDark = Color(0xFFCEE9DB)
val TertiaryDark = Color(0xFFA7CCE0)
val OnTertiaryDark = Color(0xFF0A3445)
val TertiaryContainerDark = Color(0xFF264B5C)
val OnTertiaryContainerDark = Color(0xFFC3E8FD)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE1E3DF)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE1E3DF)
